name: linter
description: Checks the code for linting errors
inputs:
  node-version:
    description: 'The version of Node.js to use'
    default: "18"
  package-manager:
    description: 'The package manager to use'
    default: "pnpm"
  pnpm-version:
    description: 'The version of pnpm to use (only applies if package-manager is pnpm)'
    default: "8.0.0"
  install-options:
    description: 'The options to pass to the package manager install command'
    default: "--ignore-scripts"
  lint-options:
    description: 'The options to pass to the package manager lint command'
    default: ""
runs:
  using: composite
  steps:
    - name: Install pnpm
      if: ${{ inputs.package-manager == 'pnpm' }}
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}
    
    - name: Install Node.js and setup dependency caching
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}.x
        cache: '${{ inputs.package-manager }}'
    
    - name: Install dependencies
      run: ${{ inputs.package-manager }} install ${{ inputs.install-options }}
      shell: bash

    - name: Run linter
      run: ${{ inputs.package-manager }} run lint ${{ inputs.lint-options }}
      shell: bash
