name: commitlint
description: Checks commit messages for compliance with the conventional commit standard
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.0.0
    
    - name: Install Node.js 18 and setup dependency caching
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
        cache: 'pnpm'

    - name: Check commitlint.config.cjs
      # description: Checks if the commitlint.config.cjs file is not present in the PR, add it.
      run: |
        if [ ! -f commitlint.config.cjs ]; then
          curl -o commitlint.config.cjs https://raw.githubusercontent.com/sliit-foss/actions/main/commitlint.config.cjs
        fi
      shell: bash

    - name: Setup commitlint
      run: pnpm install --save-dev @commitlint/cli @commitlint/config-conventional
      shell: bash

    - name: Run commitlint
      run: pnpm run commitlint --edit --color
      shell: bash
