name: clean
description: Removes the preview directory
runs:
  using: composite
  steps:
    - name: Download PR number artifact 📦
      uses: actions/github-script@v3.1.0
      with:
        script: |
          var artifacts = await github.actions.listWorkflowRunArtifacts({
             owner: context.repo.owner,
             repo: context.repo.repo,
             run_id: ${{github.event.workflow_run.id }},
          });
          var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "prnumber"
          })[0];
          var download = await github.actions.downloadArtifact({
             owner: context.repo.owner,
             repo: context.repo.repo,
             artifact_id: matchArtifact.id,
             archive_format: 'zip',
          });
          var fs = require('fs');
          fs.writeFileSync('${{github.workspace}}/prnumber.zip', Buffer.from(download.data));

    - name: Unzip PR number artifact 📦
      run: |
        unzip prnumber.zip
        echo "pr-number=$(cat prnumber.txt)" >> "$GITHUB_ENV"
      shell: bash

    - name: Set up Python 3 🐍
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Clean preview 🧹
      uses: akalanka47000/pr-preview-action@main
      with:
        action: remove
        pr-number: ${{ env.pr-number }}
        umbrella-dir: preview
