name: formatter
description: Checks the code for formatting errors
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.0.0
    
    - name: Install Node.js 18 and setup dependency caching
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install --ignore-scripts
      shell: bash

    - name: Run formatter
      run: pnpm run format
      shell: bash

    - name: Check file changers
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'chore: format code'
        add: '**/*'
